### PR TITLE
Fix schedule page

### PR DESCRIPTION
**Pull request by tsriram**
This PR fixes the schedule page 🎉  

Main changes are:

1. Upgrade `Astro` to the current latest version (0.13.10) which seems to fix the issues with the collection API
2. Fix the `createCollection` function
    - `data` should return an array. In this case, we need to filter the `episodes` variable and return an array that contains only the episode that matches the `slug`. `data` function gets `params` as a parameter. ([docs](https://github.com/snowpackjs/astro/blob/main/docs/api.md#createcollection))
    - `permalink` also gets `params` object that contains the object we return from `routes` function. We need to use `slug` from the `params` object and not direction.
 3. No big change in HTML, just some formatting. 

@jlengstorf @FredKSchott

### CODE REVIEW

**Comment by tsriram** [comment]
Oops, didn't realize that @luispinto23 already had a [PR](https://github.com/learnwithjason/lets-learn-astro/pull/1) for this 😄

**Comment by luispinto23** [comment]
> Oops, didn't realize that @luispinto23 already had a [PR](https://github.com/learnwithjason/lets-learn-astro/pull/1) for this 😄

No problem, yours is more complete and addresses the Astro version 👌

**Comment by FredKSchott** [comment]
LGTM! sad to lose the “help me jebus” console log 😄

**Review by jlengstorf — APPROVED** [review]
thank you!

**Pull request merged**
